services:
  playmodoro:
    container_name: playmodoro
    build: ./compose/frontend
    env_file:
      - .env
    ports:
      - "8080:80"
      - "3000:3000"
    restart: always
    volumes:
      - ./compose/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - "./src/frontend:/src"
    networks:
      - playmodoro-network
  media-api:
    container_name: media-api
    build: ./compose/backend
    env_file:
      - .env
    ports:
      - "8081:80"
    # environment:
    #   YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    restart: always
    volumes:
      - ./compose/backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./compose/backend/php-fpm.conf:/etc/php83/php-fpm.d/www.conf
      - "./src/backend:/var/www/html"
    networks:
      - playmodoro-network
networks:
  playmodoro-network:
    name: playmodoro-network
